# Generated by Django 5.0.7 on 2024-07-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='no_of_correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
