# Generated by Django 5.0.7 on 2024-07-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_challenge_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
